### ISSUE TITLE
can we get easier to parse semver tag

### ISSUE THREAD

**Issue by yazug** [rcritten/puppet-nssdb#5]
release-1-0-1 is difficult to parse, might we be able to get tags more like "1.0.1"  to make automation around consuming this repo easier?

RDO Trunk master is grabbing version for this package as "release"

puppet-nssdb-release-0.20160804182612.b9e3de3.el7.centos.src.rpm

https://github.com/openstack-packages/DLRN/blob/master/scripts/common-functions#L9-L42

**Comment by rcritten** [comment]
Not to be too defensive but I fail to see how this is difficult to parse or how it is somehow insane.

So you want me to add a duplicate tag to match your expected versioning scheme?

**Comment by yazug** [comment]
Wondering if it would be possible for puppet-nssdb to use a slightly different tagging scheme, if you are opposed to adopting that then, we will just have to add yet another version tag scheme into RDO dlrn logic to parse this format.

**Comment by rcritten** [comment]
Done.
